#ifndef __C_PACKET_OPCODES_
#define __C_PACKET_OPCODES_

#include "cIncludes.h"

#include "cClusterSession.h"

enum cPckOpcodes
{
	C_CMSG_NULL						= 0x00, //0x00
	C_CMSG_PING,
	C_SMSG_PING_RESP,
	C_SMSG_PING,
	C_CMSG_PING_RESP,
	C_SMSG_CLUSTER_TYPE,
	C_CMSG_GET_LOOTS,
	C_SMSG_GET_LOOTS,
	C_SMSG_RETRANSMIT_PACKET,
	C_SMSG_RETRANSMIT_PACKET_ON_LIST,
	C_SMSG_GET_UINT64,
	C_SMSG_GET_V_UINT64,
	C_SMSG_GET_BOOL,
	C_SMSG_GET_UINT32,
	C_SMSG_GET_FLOAT,
	C_SMSG_GET_INT32,

	MAX_C_OPCODES,
};

#endif