# Copyright (C) 2005-2008 MaNGOS <http://getmangos.com/>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

## Process this file with automake to produce Makefile.in

## Sub-directories to parse

## Additional files to include when running 'make dist'
#  G3DLite header files
EXTRA_DIST = \
	g3dlite/G3D/AABox.h \
	g3dlite/G3D/Array.h \
	g3dlite/G3D/Box.h \
	g3dlite/G3D/CollisionDetection.h \
	g3dlite/G3D/CoordinateFrame.h \
	g3dlite/G3D/Crypto.h \
	g3dlite/G3D/debug.h \
	g3dlite/G3D/format.h \
	g3dlite/G3D/g3dmath.h \
	g3dlite/G3D/g3dmath.inl \
	g3dlite/G3D/GCamera.h \
	g3dlite/G3D/Line.h \
	g3dlite/G3D/Matrix3.h \
	g3dlite/G3D/Plane.h \
	g3dlite/G3D/platform.h \
	g3dlite/G3D/Quat.h \
	g3dlite/G3D/Quat.inl \
	g3dlite/G3D/Ray.h \
	g3dlite/G3D/RegistryUtil.h \
	g3dlite/G3D/Sphere.h \
	g3dlite/G3D/stringutils.h \
	g3dlite/G3D/System.h \
	g3dlite/G3D/Table.h \
	g3dlite/G3D/Triangle.h \
	g3dlite/G3D/Vector2.h \
	g3dlite/G3D/Vector2.inl \
	g3dlite/G3D/Vector2int16.h \
	g3dlite/G3D/Vector3.h \
	g3dlite/G3D/Vector3.inl \
	g3dlite/G3D/Vector3int16.h \
	g3dlite/G3D/Vector4.h \
	g3dlite/G3D/Vector4.inl

#  MySQL header files for Win32 builds
EXTRA_DIST += \
	mysql/config-netware.h \
	mysql/config-os2.h \
	mysql/config-win.h \
	mysql/errmsg.h \
	mysql/libmysqld.def \
	mysql/Libmysql.def \
	mysql/m_ctype.h \
	mysql/m_string.h \
	mysql/my_alloc.h \
	mysql/my_dbug.h \
	mysql/my_getopt.h \
	mysql/my_global.h \
	mysql/my_list.h \
	mysql/my_pthread.h \
	mysql/mysql_com.h \
	mysql/mysqld_error.h \
	mysql/mysql_embed.h \
	mysql/mysql.h \
	mysql/mysql_time.h \
	mysql/mysql_version.h \
	mysql/my_sys.h \
	mysql/raid.h \
	mysql/typelib.h

#  OpenSSL header files for Win32 builds
EXTRA_DIST += \
	openssl/aes.h \
	openssl/asn1.h \
	openssl/asn1_mac.h \
	openssl/asn1t.h \
	openssl/bio.h \
	openssl/blowfish.h \
	openssl/bn.h \
	openssl/buffer.h \
	openssl/cast.h \
	openssl/comp.h \
	openssl/conf_api.h \
	openssl/conf.h \
	openssl/crypto.h \
	openssl/des.h \
	openssl/des_old.h \
	openssl/dh.h \
	openssl/dsa.h \
	openssl/dso.h \
	openssl/dtls1.h \
	openssl/ebcdic.h \
	openssl/ecdh.h \
	openssl/ecdsa.h \
	openssl/ec.h \
	openssl/engine.h \
	openssl/e_os2.h \
	openssl/err.h \
	openssl/evp.h \
	openssl/hmac.h \
	openssl/idea.h \
	openssl/krb5_asn.h \
	openssl/kssl.h \
	openssl/lhash.h \
	openssl/md2.h \
	openssl/md4.h \
	openssl/md5.h \
	openssl/mdc2.h \
	openssl/objects.h \
	openssl/obj_mac.h \
	openssl/ocsp.h \
	openssl/opensslconf.h \
	openssl/opensslv.h \
	openssl/ossl_typ.h \
	openssl/pem2.h \
	openssl/pem.h \
	openssl/pkcs12.h \
	openssl/pkcs7.h \
	openssl/pq_compat.h \
	openssl/pqueue.h \
	openssl/rand.h \
	openssl/rc2.h \
	openssl/rc4.h \
	openssl/rc5.h \
	openssl/ripemd.h \
	openssl/rsa.h \
	openssl/safestack.h \
	openssl/sha.h \
	openssl/ssl23.h \
	openssl/ssl2.h \
	openssl/ssl3.h \
	openssl/ssl.h \
	openssl/stack.h \
	openssl/store.h \
	openssl/symhacks.h \
	openssl/tls1.h \
	openssl/tmdiff.h \
	openssl/txt_db.h \
	openssl/ui_compat.h \
	openssl/ui.h \
	openssl/x509.h \
	openssl/x509v3.h \
	openssl/x509_vfy.h

#  PostgreSQL header files for Win32 builds
EXTRA_DIST += \
	postgre/libpq-fe.h \
	postgre/pg_type.h \
	postgre/postgres_ext.h

#  Sockets header files for Win32 builds
EXTRA_DIST += \
	sockets\Base64.h \
	sockets\CircularBuffer.h \
	sockets\IFile.h \
	sockets\Ipv4Address.h \
	sockets\Ipv6Address.h \
	sockets\ISocketHandler.h \
	sockets\ListenSocket.h \
	sockets\Mutex.h \
	sockets\Parse.h \
	sockets\RandomNumber.h \
	sockets\ResolvServer.h \
	sockets\ResolvSocket.h \
	sockets\SctpSocket.h \
	sockets\Socket.h \
	sockets\socket_include.h \
	sockets\SocketAddress.h \
	sockets\SocketHandler.h \
	sockets\sockets-config.h \
	sockets\StdLog.h \
	sockets\StdoutLog.h \
	sockets\TcpSocket.h \
	sockets\Thread.h \
	sockets\UdpSocket.h \
	sockets\Uid.h \
	sockets\Utility.h

#  VLD header files for Win32 builds
EXTRA_DIST += \
	vld/vld.h

#  Zlib header files for Win32 builds
EXTRA_DIST += \
	zlib/zconf.h \
	zlib/zlib.h

# Mersenne Twister random number generator header files
EXTRA_DIST += \
	mersennetwister/MersenneTwister.h

# UTF8-CPP header files
EXTRA_DIST += \
	utf8cpp/utf8.h \
	utf8cpp/utf8/checked.h \
	utf8cpp/utf8/core.h \
	utf8cpp/utf8/unchecked.h

# RCF SF
EXTRA_DIST += \
	SF/AdlWorkaround.hpp \
	SF/INativeBinaryStream.hpp \
	SF/OBinaryStream.hpp \
	SF/SerializeDynamicArray.hpp \
	SF/SerializeStl.hpp \
	SF/tuple.hpp \
	SF/any.hpp \
	SF/I_Stream.hpp \
	SF/ONativeBinaryStream.hpp \
	SF/SerializeFundamental.hpp \
	SF/set.hpp \
	SF/utility.hpp \
	SF/Archive.hpp \
	SF/ITextStream.hpp \
	SF/OTextStream.hpp \
	SF/SerializeParent.hpp \
	SF/SfNew.hpp \
	SF/variant.hpp \
	SF/DataPtr.hpp \
	SF/list.hpp \
	SF/PortableTypes.hpp \
	SF/SerializePolymorphic.hpp \
	SF/shared_ptr.hpp \
	SF/vector.hpp \
	SF/deque.hpp \
	SF/map.hpp \
	SF/Registry.hpp \
	SF/Serializer.hpp \
	SF/Stream.hpp \
	SF/wstring.hpp \
	SF/Encoding.hpp \
	SF/memory.hpp \
	SF/scoped_ptr.hpp \
	SF/SerializeSmartPtr.hpp \
	SF/string.hpp \
	SF/IBinaryStream.hpp \
	SF/Node.hpp \
	SF/SerializeAny.hpp \
	SF/SerializeStaticArray.hpp \
	SF/Tools.hpp \
	RCF/Amd.hpp \
	RCF/IpServerTransport.hpp \
	RCF/StubEntry.hpp \
	RCF/AmiThreadPool.hpp \
	RCF/Marshal.hpp \
	RCF/StubFactory.hpp \
	RCF/Asio.hpp \
	RCF/MethodInvocation.hpp \
	RCF/SubscriptionService.hpp \
	RCF/AsioServerTransport.hpp \
	RCF/MulticastClientTransport.hpp \
	RCF/TcpAsioServerTransport.hpp \
	RCF/AsyncFilter.hpp \
	RCF/NamedPipeEndpoint.hpp \
	RCF/TcpClientTransport.hpp \
	RCF/BsAutoPtr.hpp \
	RCF/ObjectFactoryService.hpp \
	RCF/TcpEndpoint.hpp \
	RCF/BsdClientTransport.hpp \
	RCF/ObjectPool.hpp \
	RCF/TcpIocpServerTransport.hpp \
	RCF/ByteBuffer.hpp \
	RCF/OpenSslEncryptionFilter.hpp \
	RCF/ByteOrdering.hpp \
	RCF/PerformanceData.hpp \
	RCF/ThreadLibrary.hpp \
	RCF/CheckRtti.hpp \
	RCF/PingBackService.hpp \
	RCF/ThreadLocalCache.hpp \
	RCF/ClientProgress.hpp \
	RCF/ThreadLocalData.hpp \
	RCF/ClientStub.hpp \
	RCF/ThreadManager.hpp \
	RCF/ClientTransport.hpp \
	RCF/PublishingService.hpp \
	RCF/TimedBsdSockets.hpp \
	RCF/ConnectionOrientedClientTransport.hpp \
	RCF/Random.hpp \
	RCF/Token.hpp \
	RCF/CurrentSerializationProtocol.hpp \
	RCF/Tools.hpp \
	RCF/CurrentSession.hpp \
	RCF/RcfClient.hpp \
	RCF/TypeTraits.hpp \
	RCF/EndpointBrokerService.hpp \
	RCF/RCF.hpp \
	RCF/UdpClientTransport.hpp \
	RCF/Endpoint.hpp \
	RCF/RcfServer.hpp \
	RCF/UdpEndpoint.hpp \
	RCF/EndpointServerService.hpp \
	RCF/RcfSession.hpp \
	RCF/UdpServerTransport.hpp \
	RCF/Exception.hpp \
	RCF/RecursionLimiter.hpp \
	RCF/UnixLocalClientTransport.hpp \
	RCF/Export.hpp \
	RCF/Schannel.hpp \
	RCF/UnixLocalEndpoint.hpp \
	RCF/FileTransferService.hpp \
	RCF/SerializationDefs.hpp \
	RCF/UnixLocalServerTransport.hpp \
	RCF/FilterService.hpp \
	RCF/SerializationProtocol.hpp \
	RCF/UsingOpenSsl.hpp \
	RCF/GetInterfaceName.hpp \
	RCF/ServerInterfaces.hpp \
	RCF/Heap.hpp \
	RCF/ServerStub.hpp \
	RCF/Version.hpp \
	RCF/Idl.hpp \
	RCF/ServerTask.hpp \
	RCF/Win32NamedPipeClientTransport.hpp \
	RCF/InitDeinit.hpp \
	RCF/ServerTransport.hpp \
	RCF/Win32NamedPipeEndpoint.hpp \
	RCF/Iocp.hpp \
	RCF/Service.hpp \
	RCF/Win32NamedPipeServerTransport.hpp \
	RCF/IocpServerTransport.hpp \
	RCF/SessionObjectFactoryService.hpp \
	RCF/ZlibCompressionFilter.hpp \
	RCF/IpAddress.hpp \
	RCF/SessionTimeoutService.hpp \
	RCF/IpClientTransport.hpp \
	RCF/Protocol/BoostSerialization.hpp \
	RCF/Protocol.hpp \
	RCF/Protocol/SF.hpp \
	RCF/RcfBoostThreads/RcfBoostThreads.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/barrier.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/condition.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/exceptions.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/mutex.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/once.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/thread.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/tss.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/xtime.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/detail/config.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/detail/force_cast.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/detail/lock.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/detail/singleton.hpp \
	RCF/RcfBoostThreads/boost_1_33_1/boost/thread/detail/tss_hooks.hpp \
	RCF/test/DisableGpfDialog.hpp \
	RCF/test/PrintTestHeader.hpp \
	RCF/test/TestMinimal.hpp \
	RCF/test/Usernames.hpp \
	RCF/test/MiniDump.cpp \
	RCF/test/ProgramTimeLimit.hpp \
	RCF/test/ThreadGroup.hpp \
	RCF/test/WithStopServer.hpp \
	RCF/test/MiniDump.hpp \
	RCF/test/SpCollector.hpp \
	RCF/test/TransportFactories.hpp \
	RCF/util/Assert.hpp \
	RCF/util/DefaultInit.hpp \
	RCF/util/PrePostCondition.hpp \
	RCF/util/ThreadLibrary.hpp \
	RCF/util/TraceTargetFileRollOver.hpp \
	RCF/util/AutoBuild.hpp \
	RCF/util/GetLocalIps.hpp \
	RCF/util/Profile.hpp \
	RCF/util/Throw.hpp \
	RCF/util/UnusedVariable.hpp \
	RCF/util/AutoRun.hpp \
	RCF/util/InitDeinit.hpp \
	RCF/util/Scan.hpp \
	RCF/util/TraceCommandLineOption.hpp \
	RCF/util/VariableArgMacro.hpp \
	RCF/util/CommandLine.hpp \
	RCF/util/Tchar.hpp \
	RCF/util/Trace.hpp \
	RCF/util/Platform/Threads/BoostThreads.hpp \
	RCF/util/Platform/Threads/RcfBoostThreads.hpp \
	RCF/util/Platform/Threads/ThreadsProxy.hpp
	RCF/util/Platform/OS/BsdSockets.hpp \
	RCF/util/Platform/OS/OutputDebugString.hpp \
	RCF/util/Platform/OS/ThreadId.hpp \
	RCF/util/Platform/OS/Unix_Common.hpp \
	RCF/util/Platform/OS/GetCurrentTime.hpp \
	RCF/util/Platform/OS/Sleep.hpp \
	RCF/util/Platform/Machine/ByteOrder.hpp 
