// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __FirstCallBack_hh__
#define __FirstCallBack_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __FirstCallBack__
#define __FirstCallBack__

class FirstCallBack;
class _objref_FirstCallBack;
class _impl_FirstCallBack;

typedef _objref_FirstCallBack* FirstCallBack_ptr;
typedef FirstCallBack_ptr FirstCallBackRef;

class FirstCallBack_Helper {
public:
  typedef FirstCallBack_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_FirstCallBack, FirstCallBack_Helper> FirstCallBack_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_FirstCallBack,FirstCallBack_Helper > FirstCallBack_out;

#endif

// interface FirstCallBack
class FirstCallBack {
public:
  // Declarations for this interface type.
  typedef FirstCallBack_ptr _ptr_type;
  typedef FirstCallBack_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_FirstCallBack :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  char* nerzhulCB(const char* tototutu);

  inline _objref_FirstCallBack()  { _PR_setobj(0); }  // nil
  _objref_FirstCallBack(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_FirstCallBack();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_FirstCallBack(const _objref_FirstCallBack&);
  _objref_FirstCallBack& operator = (const _objref_FirstCallBack&);
  // not implemented

  friend class FirstCallBack;
};

class _pof_FirstCallBack : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_FirstCallBack() : _OMNI_NS(proxyObjectFactory)(FirstCallBack::_PD_repoId) {}
  virtual ~_pof_FirstCallBack();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_FirstCallBack :
  public virtual omniServant
{
public:
  virtual ~_impl_FirstCallBack();

  virtual char* nerzhulCB(const char* tototutu) = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};




class POA_FirstCallBack :
  public virtual _impl_FirstCallBack,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_FirstCallBack();

  inline ::FirstCallBack_ptr _this() {
    return (::FirstCallBack_ptr) _do_this(::FirstCallBack::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
FirstCallBack::_marshalObjRef(::FirstCallBack_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_FirstCallBack
#endif

#endif  // __FirstCallBack_hh__

