// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "FirstCallBack.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



FirstCallBack_ptr FirstCallBack_Helper::_nil() {
  return ::FirstCallBack::_nil();
}

::CORBA::Boolean FirstCallBack_Helper::is_nil(::FirstCallBack_ptr p) {
  return ::CORBA::is_nil(p);

}

void FirstCallBack_Helper::release(::FirstCallBack_ptr p) {
  ::CORBA::release(p);
}

void FirstCallBack_Helper::marshalObjRef(::FirstCallBack_ptr obj, cdrStream& s) {
  ::FirstCallBack::_marshalObjRef(obj, s);
}

FirstCallBack_ptr FirstCallBack_Helper::unmarshalObjRef(cdrStream& s) {
  return ::FirstCallBack::_unmarshalObjRef(s);
}

void FirstCallBack_Helper::duplicate(::FirstCallBack_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

FirstCallBack_ptr
FirstCallBack::_duplicate(::FirstCallBack_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

FirstCallBack_ptr
FirstCallBack::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


FirstCallBack_ptr
FirstCallBack::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

FirstCallBack_ptr
FirstCallBack::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_FirstCallBack _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_FirstCallBack* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_FirstCallBack;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* FirstCallBack::_PD_repoId = "IDL:FirstCallBack:1.0";


_objref_FirstCallBack::~_objref_FirstCallBack() {
  
}


_objref_FirstCallBack::_objref_FirstCallBack(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::FirstCallBack::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_FirstCallBack::_ptrToObjRef(const char* id)
{
  if( id == ::FirstCallBack::_PD_repoId )
    return (::FirstCallBack_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::FirstCallBack::_PD_repoId) )
    return (::FirstCallBack_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cstring_i_cstring
class _0RL_cd_052172E14A861172_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_052172E14A861172_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var result;
};

void _0RL_cd_052172E14A861172_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_052172E14A861172_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_052172E14A861172_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_052172E14A861172_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_052172E14A861172_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_052172E14A861172_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_052172E14A861172_00000000* tcd = (_0RL_cd_052172E14A861172_00000000*)cd;
  _impl_FirstCallBack* impl = (_impl_FirstCallBack*) svnt->_ptrToInterface(FirstCallBack::_PD_repoId);
  tcd->result = impl->nerzhulCB(tcd->arg_0);


}

char* _objref_FirstCallBack::nerzhulCB(const char* tototutu)
{
  _0RL_cd_052172E14A861172_00000000 _call_desc(_0RL_lcfn_052172E14A861172_10000000, "nerzhulCB", 10);
  _call_desc.arg_0 = tototutu;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
_pof_FirstCallBack::~_pof_FirstCallBack() {}


omniObjRef*
_pof_FirstCallBack::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_FirstCallBack(ior, id);
}


::CORBA::Boolean
_pof_FirstCallBack::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::FirstCallBack::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_FirstCallBack _the_pof_FirstCallBack;

_impl_FirstCallBack::~_impl_FirstCallBack() {}


::CORBA::Boolean
_impl_FirstCallBack::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "nerzhulCB") ) {

    _0RL_cd_052172E14A861172_00000000 _call_desc(_0RL_lcfn_052172E14A861172_10000000, "nerzhulCB", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_FirstCallBack::_ptrToInterface(const char* id)
{
  if( id == ::FirstCallBack::_PD_repoId )
    return (::_impl_FirstCallBack*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::FirstCallBack::_PD_repoId) )
    return (::_impl_FirstCallBack*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_FirstCallBack::_mostDerivedRepoId()
{
  return ::FirstCallBack::_PD_repoId;
}

POA_FirstCallBack::~POA_FirstCallBack() {}

