#ifndef __INSTANCE_HOR_H
#define __INSTANCE_HOR_H

enum Types
{
	TYPE_FALRIC				=	0,
	TYPE_MARWYN				=	1,
	TYPE_LICHKING			=	2,
	TYPE_FACTIONLEADER_EV1	=	3,
	TYPE_FACTIONLEADER_EV2	=	4,	

	TYPE_EVENT_FROSTMOURNE	=	10,
	TYPE_EVENT_ESCAPE		=	11,

	DATA_DOOR_MAIN			=	20,
	DATA_DOOR_LICHKING		=	21,

	DATA_RANDOM_WARRIOR		=	30,
	DATA_RANDOM_MAGE		=	31,
	DATA_RANDOM_PRIEST		=	32,
	DATA_RANDOM_HUNT		=	33,
	DATA_RANDOM_ROGUE		=	34,

	WS_MAIN					=	4884,
	WS_VAGUE				=	4882,
};
#endif